### ISSUE TITLE
Rust: Add pre-development stub

### ISSUE THREAD

**Issue by Smiddie31** [Skenvy/Collatz#41]
### What would you like to be added?

A rust version of the collatz package

### Why is this needed?

No module is complete without a rust version.

**Comment by Skenvy** [comment]
I'd be happy to consider adding one; although a package with the "collatz" name already seems to exist -- https://crates.io/crates/collatz, that didn't stop the C# or npm from being added, so this should also be included!

**Comment by Skenvy** [comment]
I'm happy to add this to the roadmap, although will likely happen after the Ruby and R implementations, as they don't have existing named packages for this yet. See https://github.com/Skenvy/Collatz/blob/main/ADD_LANG.md for how to add a stub!

**Comment by Skenvy** [comment]
Feel free to bypass most of the README template in that, as this is a pre-development stub, only the first two lines of the readme template are expected, along with comments about the existing package and the repository that it comes from --  see https://github.com/Skenvy/Collatz/blob/main/C%23/README.md for an example of this.

**Comment by Skenvy** [comment]
From this issue https://github.com/rust-lang/rust/issues/100000 ; accepting the Rust emoji's as "❤️🦀❤️"
